name: Build and publish binaries
on:
  release:
    types:
      - created
jobs:
  build:
    name: Build and publish binaries
    strategy:
      matrix:
        go-version: [ 1.17.x ]
        platform: [ ubuntu-latest ]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Check out code
      uses: actions/checkout@v2
    - name: Build Binary for linux amd64
      run: go build -o lndhub-${{github.event.release.tag_name}}-linux-x86_64
    - name: Build Binary for linux arm v7
      run: GOOS=linux GOARCH=arm GOARM=7 go build -o lndhub-${{github.event.release.tag_name}}-linux-arm_v7
    - name: Upload amd64 binary to release assets
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./lndhub-${{github.event.release.tag_name}}-linux-x86_64
        asset_name: lndhub-${{github.event.release.tag_name}}-linux-x86_64
        asset_content_type: binary/octet-stream
    - name: Upload armv7 binary to release assets
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./lndhub-${{github.event.release.tag_name}}-linux-arm_v7
        asset_name: lndhub-${{github.event.release.tag_name}}-linux-arm_v7
        asset_content_type: binary/octet-stream
