name: Build and publish binaries
on:
  push:
    tags:
      - '*'
jobs:
  build:
    name: Build and publish binaries
    strategy:
      matrix:
        go-version: [ 1.16.x ]
        platform: [ ubuntu-latest ]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Build Binary for linux
      run: go build -o lndhub-${{github.event.release.tag_name}}linux-x86_64
    - name: Upload to release assets
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./lndhub-${{github.event.release.tag_name}}linux-x86_64
        asset_name: lndhub-${{github.event.release.tag_name}}linux-x86_64
        asset_content_type: binary/octet-stream